### ISSUE TITLE
Send description confusing

### ISSUE THREAD

**Issue by james-lawrence** [go-mangos/mangos#176]
```go
	// Send puts the message on the outbound send.  It always succeeds,
	// unless the buffer(s) are full.  Once the system takes ownership of
	// the message, it guarantees to deliver the message or keep trying as
	// long as the Socket is open.
	Send([]byte) error
```
The guarantee to deliver the message or keep trying is false if WriteQLen is > 0.
assuming I send two messages "foo" "bar" to an unresponsive endpoint. I expect two failures,
instead I get 1.

```go
package main

import (
	"fmt"
	"log"
	"os"
	"time"

	"github.com/gdamore/mangos"
	"github.com/gdamore/mangos/protocol/push"
	"github.com/gdamore/mangos/transport/ipc"
	"github.com/gdamore/mangos/transport/tcp"
)

func die(format string, v ...interface{}) {
	fmt.Fprintln(os.Stderr, fmt.Sprintf(format, v...))
	os.Exit(1)
}

func NewPool(urls ...string) mangos.Socket {
	var sock mangos.Socket
	var err error
	if sock, err = push.NewSocket(); err != nil {
		die("can't get new push socket: %s", err.Error())
	}

	sock.AddTransport(ipc.NewTransport())
	sock.AddTransport(tcp.NewTransport())

	sock.SetOption(mangos.OptionWriteQLen, 1)
	for _, url := range urls {
		if err = sock.Dial(url); err != nil {
			die("can't dial on push socket: %s", err.Error())
		}
	}
	return sock
}

func Send(s mangos.Socket, msgs ...string) {
	for _, msg := range msgs {
		s.SetOption(mangos.OptionSendDeadline, 100*time.Millisecond)
		if err := s.Send([]byte(msg)); err != nil {
			log.Println(msg, "failed:", err)
		}
	}

	if err := s.Close(); err != nil {
		log.Println("Failed Close", err)
	}
}

func main() {
	Send(NewPool("tcp://127.0.0.1:8080"), "foo", "bar")
}
```

```bash
$ ./bin/failure 
2016/01/07 11:18:43 bar failed: send time out
```

**Comment by gdamore** [comment]
So, with a non-zero queue depth, we will queue the messages immediately, even if there is no where for them to get.  The message is still dropped on the floor, but there is no notification back to the app.  This is the drawback of using a non-zero queue depth.

The comment does need to be fixed though.

**Comment by gdamore** [comment]
Actually, the comment is right.  Going back it does exactly what it says.

The message fails immediately if the queue is full, otherwise the system queues it for later delivery, and will keep attempting to deliver the message ~forever.  Basically, the queue length is the size of a channel, and we leave the message in the channel.

There is a special exception made for messages that have a deadline.  In that case, we may later discard the message instead of delivering it, if we find that the message's deadline has expired.  Again this occurs without notification to the app.

The comment can be clarified somewhat to make this easier to understand.

**Comment by james-lawrence** [comment]
I think the documentation should further expanded to describe how to achieve reliable delivery (i.e. set to 0 queue length to 0), I'll whip up a PR for this.

Not sure I agree that the comment was correct. But I understand what you are getting at.
It would be nice for there to be an error on Close if there are messages left in the channel. i.e. shutdown the network connections and len(c).

This behaviour exists leads me to question if the transports are properly cleaned up prior to the Close function returning. I'll read the code for that later.

**Comment by nickpoorman** [comment]
> It would be nice for there to be an error on Close if there are messages left in the channel. i.e. shutdown the transport connections and len(c).

@james-lawrence - I agree. There should be some sort of error returned specifying that there is data still waiting to send. For example, if I have a push socket and there is no pull socket connected, the push socket will lose data if it closes after the timeout.

A more reasonable approach after calling `Close()` on the socket would be to return some sort of error (or the data left in the queue) after the timeout, so that the consumer of the mangos api can do something with the data instead of just losing it forever.

@gdamore - I'm curious how other people handle gracefully closing a socket so they don't lose data. Does setting `sock.SetOption(mangos.OptionWriteQLen, 0)` prevent this problem?
