### ISSUE TITLE
Benchmark test times out after 10 minutes on OSX

### ISSUE THREAD

**Issue by nkev** [go-mangos/mangos#177]
I ran `go get -u github.com/go-mangos/mangos` successfully.

I then ran `go test -bench=. github.com/go-mangos/mangos/test` and it timed out after 10 minutes. Tried again with same result. 

Macbook Pro Retina Late 2013 with SSD, 2.6GHz I7, running OSX 10.11.2 El Capitan

**Comment by gdamore** [comment]
Yes, the benchmark is busted, I noticed yesterday, I need to work on it, as I'm not sure what is broken, it seems to be hanging.

**Comment by nkev** [comment]
I love the library, I'm trying to find out how Mangos roughly performs (msgs/sec in/out) in comparison to Nanomsg and ZeroMQ. You may have seen [this](http://bravenewgeek.com/tag/gnatsd/) benchmark test. 

I also like the brokered [GNATSD](https://github.com/nats-io/gnatsd) system. It sounds very robust and claims 6-8 million messages a second on a single machine.


Have you done any benchmarking, especially against other messaging platforms?

**Comment by nkev** [comment]
anyone?

**Comment by gdamore** [comment]
Sorry, just haven’t had time.  The failure is new, and I’m not sure if it
was introduced on newer MacOS X, or newer Go, or in code changes I made.

**Comment by nkev** [comment]
No, that's cool. I was asking if there were any benchmark results, especially against Nanomsg, ZeroMQ or NATS.

**Comment by gdamore** [comment]
I'm working to isolate the problem.  It seems pretty consistent, although what is happening is that the socket receive times out when it should not.  (If I add a timeout.)  The number of messages exchanged before timeout varies though, and running the full test before seems to make the incident rate much higher than running the benchmarks in isolation.

(As an aside, I think there are also performance regressions here.)

**Comment by gdamore** [comment]
So the regression was caused here: b0e8c6116fe95e25a6959c2653daefe433778f5e

The problem is that we wind up stuck inside a loop, trashing the message list and doing other "bad" things, as we leave one thread in an infinite loop chewing (and refreeing message).

Here's the diff to fix:

```
diff --git a/protocol/respondent/respondent.go b/protocol/respondent/respondent.go
index 23432ef..87d4426 100644
--- a/protocol/respondent/respondent.go
+++ b/protocol/respondent/respondent.go
@@ -130,6 +130,7 @@ func (x *resp) receiver(ep mangos.Endpoint) {
        rq := x.sock.RecvChannel()
        cq := x.sock.CloseChannel()
 
+outer:
        for {
                m := ep.RecvMsg()
                if m == nil {
@@ -144,12 +145,12 @@ func (x *resp) receiver(ep mangos.Endpoint) {
                for {
                        if hops >= x.ttl {
                                m.Free() // ErrTooManyHops
-                               continue
+                               continue outer
                        }
                        hops++
                        if len(m.Body) < 4 {
                                m.Free()
-                               continue
+                               continue outer
                        }
                        m.Header = append(m.Header, m.Body[:4]...)
                        m.Body = m.Body[4:]
```

**Comment by gdamore** [comment]
FYI, with respect to performance.  mangos performs comparably to nanomsg in just about all cases.  One way latencies through the TCP stack (loopback) are about 20 us end to end for REQ/REP with 128 byte frames on my iMac, but it should get very good horizontal scalability on much larger systems.  I've not written a test specifically for this, but to give you a sense, on his system, the author of the test suite found that nanomsg got around 2M messages/sec.  I think on higher end systems we could go quite high indeed (depending on message size of course.)

On the same system, GNATS also got about 200K msgs/sec.  Brokered systems fare poorly from a performance standpoint against brokerless.  You don't choose a brokered system because of performance, you choose it for other reasons.

I expect that mangos would probably get more than 5x, and possibly as much as 10x, the performance of GNATS on the same system.  I've not measured that, but I'd welcome figures.

**Comment by gdamore** [comment]
More detail here: http://bravenewgeek.com/dissecting-message-queues/

**Comment by nkev** [comment]
Thank you for your reply.
