### ISSUE TITLE
Production use?

### ISSUE THREAD

**Issue by nkev** [go-mangos/mangos#185]
Is anyone using Mangos in production? If so, what transports and protocols are you using? Please share your experience for the benefit of others who are evaluating it.

**Comment by gdamore** [comment]
We are using it in a pre-production product.  It works well for us, where I'm using it as a transport for both an RPC (req/rep) and a service discovery (surveyor pattern) layer.

That said, this is the wrong place to gather attention from users -- instead you should ask on the nanomsg mailing list -- nanomsg@freelists.org.  Mangos shares the nanomsg mailing list, since its community is really a subset of the larger nanomsg community.

github issues (at least as we use them) are for filing defects or requests for enhancement (i.e. changes to the code), rather than for discussion.

I'm going to close this, so it doesn't count as an open "issue" (i.e. a bug that needs fixing), but if others see this and want to comment, please feel free to add it.
