### ISSUE TITLE
transport: Local/RemoteProtocol redundant in inproc and ws

### ISSUE THREAD

**Issue by grrtrr** [go-mangos/mangos#209]
It appears that `LocalProtocol()` and `RemoteProtocol()` methods in `transport/inproc/inproc.go` and `transport/ws/ws.go` are redundant, since

* `pipe` (`pipe.go`) implements both the `Endpoint` and `Port` interfaces,
* hence already provides `LocalProtocol`/`RemoteProtocol`,
* dialers/listeners are added in `core.go:dialer()` and `core.go:listener()` via `addPipe()`,
* `sock.addPipe()` calls `pipe.go:newPipe()`,
* hence the argument to `PortActionAdd` in `core.go:addPipe()` is a `pipe` struct implementing the `Port` interface.

Similarly, when `PortActionRemove` is called on the `sock.porthook` in `pipe.go:p.Close()`, the argument is a `pipe` struct implementing the `Port` interface.

As a result, it seems that the methods `LocalProtocol()` and `RemoteProtocol()` in  `transport/inproc/inproc.go` and `transport/ws/ws.go` are redundant and could be removed.

(Stumbled upon this while revising a patch sent earlier.)

**Comment by gdamore** [comment]
Uh, I don't think so.

The `pipe` is a wrapper with some common functionality around concrete implementations.  Notably, the `p.pipe` member is actually a reference to the wsPipe (or a tranpipe in the other protocols case), and just calls through to the concrete implementation.  This is important since the details of how the protocol number are exchanged vary from transport to transport.

Please have another look -- I'm pretty sure we can just "close" this issue.

**Comment by grrtrr** [comment]
Yes, my oversight. Even says so ("implements the Pipe interface") in the files. Thanks for pointing out.
