### ISSUE TITLE
[Bus Protocol] Publishing metric to self duplicates the message?

### ISSUE THREAD

**Issue by didip** [go-mangos/mangos#225]
## Reproducible Scenario
```
package main

import (
	"time"

	"github.com/go-mangos/mangos/protocol/bus"
	"github.com/go-mangos/mangos/transport/ipc"
	"github.com/go-mangos/mangos/transport/tcp"
)

func main() {
	url := "tcp://127.0.0.1:55755"

	sock, _ := bus.NewSocket()
	sock.AddTransport(ipc.NewTransport())
	sock.AddTransport(tcp.NewTransport())

	sock.Listen(url)

	// Add self to dial
	sock.Dial(url)

	// print msg
	go func() {
		for {
			msgBytes, _ := sock.Recv()

			// Receive duplicates here
			msg := string(msgBytes)
			println("Received: " + msg)
		}
	}()

	for range time.Tick(2 * time.Second) {
		println("")
		println("Sent: hello")
		sock.Send([]byte("hello"))
	}
}
```

Is this expected behavior?

## System Environment
```
OS X El Capitan 10.11.6
go version go1.7rc3 darwin/amd64
Latest master version of mangos
```

**Comment by gdamore** [comment]
This is weird, in that you've connected the socket to itself -- and I think I understand what is happening.

By doing this, you're attaching two endpoints to the socket -- and thus creating (from mangos' point of view) two endpoints.  The system allocates a random port, say "1234", and you have requested port 55755.  Mangos thinks you have one pipe with local port number 1234, and another with local port 55755.  It does not realize that these are two ends of the same port, nor does it care.

Now when you send, it broadcasts to all connected pipes, so it sends a message out on the pipe with 1234, and again on the pipe to 55755.  Because these pipes are looped to each other, the message sent at 1234 is read back on 55755, and vice versa.  You get two messages.

All of this comes about because mangos does not realize you've created this back to back connection.  (In fact, with some protocols, like REQ/REP, or PUB/SUB, this type of connection would be impossible.  Arguably its a configuration error to create this in the first place.)

Upshot is, yes, given this misconfiguration, this is indeed what you'd expect to happen.

In theory we could add code to check and notice that the remote peer is connected to the same socket, but I won't be doing that -- I don't think the complexity and risk are worth the benefits.
