### ISSUE TITLE
Document unsubscribed sub socket blocks

### ISSUE THREAD

**Issue by lthibault** [go-mangos/mangos#227]
I was just bitten by this myself.  A sub socket that is properly initialized and connected will block indefinitely until `mangos.Socket.SetOption` is called with `mangos.OptionSubscribe` and a byte prefix.

I can think of no reason to read from an unsubscribed socket (am I missing something?), so I suggest modifying the behavior of `Recv` to panic if the socket is not subscribed to a topic.

**Comment by gdamore** [comment]
That's not a bad idea... although perhaps instead of a panic an error can be issued?

However, I can imaging cases for the current behavior -- such as a receiving socket that adds and removes subscriptions later.  Since that can be done from a separate thread, there is no reason to necessarily assume the lack of any current subscriptions represents an error.  (Arguably, as a performance enhancement -- we could discard the TCP connection to save the network overhead of receiving and discarding any published streams, but it isn't clear to me that the benefit is worth the complexity.)

Perhaps this behavior should be tunable.

**Comment by binary132** [comment]
I think adding and removing subscriptions at runtime is part of the SUB use-case.

**Comment by lthibault** [comment]
@gdamore  I'm still unclear on why one would want to read from a socket prior to adding subscriptions.  Could you provide a use-case?  Regarding panics vs errors, I agree with you on second thought.

@binary132 I agree that adding and removing subscriptions at runtime is part of the SUB use case, but "don't receive anything" does not strike me as a sensible default.  I'd go out on a limb to say that in the overwhelming majority of cases, not specifying a subscription will constitute a bug.

The following two approaches each seem internally consistent to me:

1. Accept everything by default.  Receive only from subscriptions when they are specified.  Empty string matches nothing and the socket blocks.

2. Accept nothing by default.  Report an error if one attempts to read from a socket in such a state.

I like option 2 because reading from an unsubscribed socket is semantically ambiguous (as evidenced by the present issue).  As such, it seems sensible defer control to the programmer via an error value.  From there, the programmer can decide if he wants to try again or do something special.

Of course, if there's a greater design principle that I'm overlooking, please fill me in! :)

**Comment by binary132** [comment]
Use-case:

 - Set up a SUB socket.
 - Start a loop over `Recv`.  It blocks.
 - Set up a configuration watcher, perhaps something using Zookeeper.
 - When the configuration is changed, it updates the SUB's topics.
 - Messages begin to be received on the new topics.
 - Configuration changes again.  Remove topics.  `Recv` blocks again.

Consider an event watcher which only receives events when configured to do so, including an "all" topic, defaulting to no configured topics.

**Comment by lthibault** [comment]
@binary132 Perhaps such niche cases should be synchronized outside of mangos?  e.g. with a channel?

To be clear, I'm playing devil's advocate.  My reasoning is that I can't be alone in being surprised by the default behavior, and I am therefore inclined to call it "code smell".

What would you think of returning an error in such cases -- something like `ErrNoSubs`, which the user can choose to ignore?  This way the current behavior is preserved, but the behavior is more explicitly signaled.

**Comment by gdamore** [comment]
Actually, the existing behavior is most consistent -- the socket blocks until something you've asked for arrives.  If you don't ask for anything at all (no subscription), then the block is persistent -- at least until you do add a subscription.  (As noted earlier, subscriptions can be dynamically added to -- or removed from -- an active socket, and it's perfectly reasonable for a socket to transition to a state that has no subscriptions, and for that state to not necessarily be permanent.)

Adding a special case for the situation where there are no subscription seems to be less consistent, if anything.  For example, we would have to add "blocks until a message matching your subscriptions arrives, unless you have no subscriptions, in which case it returns an error (or returns everything?)."

Furthermore, requiring developers to deal with the special no subscription state outside of nanomsg / mangos feels like it goes against the philosophy these -- which is to put as little burden on developers as possible.  It destroys the convenience of this.

Most developers figure out quickly that they need to have an active subscription if you want to have data.  This particular situation is largely a newbie mistake from not being familiar with the semantics, since its very rarely the case that a developer with zero subscriptions has code in that state unintentionally.  (Generally if its not intentional, its an error in the calling application.)

This current semantic is the same that nanomsg uses (has used forever).  I believe it is the same semantic found in ZeroMQ.

I'm pretty sure that I will not be changing this semantic.

I will however review the documentation, and make sure that its clear that a socket with no subscriptions blocks forever.

**Comment by lthibault** [comment]
@gdamore All fair points, especially with regards to consistency with other implementations of SP.  Updating the documentation is definitely a reasonable approach.

Thanks for your time!
