### ISSUE TITLE
zmtp compatibility

### ISSUE THREAD

**Issue by sbinet** [go-mangos/mangos#234]
hi there,

do you mangos-ers think it would be doable (and somewhat sensible) to provide an interoperability layer with 0MQ by way of implementing the ZMTP transport protocol?

(right now, there is no complete (nor production grade) pure-go library for ZeroMQ...)

I guess I have actually 2 questions:
- is it doable/sensible ?
- what amount of work would this require ?

**Comment by gdamore** [comment]
I originally looked at implementing ZMTP and SP together.  I decided not to, because of some core differences in the protocols, and my belief that the additional complexity would not be worth it.  In particular, there are some paradigm differences that are large enough that mixing SP and ZMTP in the same patterns definitely does not make sense.

It would probably be easier to start with mangos, and write a pure Go implementation of ZMTP.  I might be convinced to do that (hint: someone paying some $$ for the work would go a long way towards convincing me), although I have enough on my plate at the moment.

**Comment by sbinet** [comment]
I have a working pub/sub example, inter-operable with C++ ZeroMQ pub/sub(s).
how do you want to proceed?
should I publish the repo on my github?
or create an empty repo under go-mangos and send a PR?

**Comment by gdamore** [comment]
You may send a PR or a pointer to code... I'd need to look at the code.  I'm highly skeptical.

**Comment by sbinet** [comment]
here it is: https://github.com/sbinet-alice/zmq

**Comment by sbinet** [comment]
this is still a PoC at this stage, but it's already somewhat working.
at least the tests are passing.

of course, more error handling, more tests, more ZMQ-RFC features to implement, etc... should be implemented.

**Comment by sbinet** [comment]
hi there,

any feedback?
do you think it is worth pursuing? (at least with the integration back under the `go-mangos` umbrella in mind)

**Comment by omani** [comment]
I want to tell that this is much appreciated and I this is very interesting to me (I am using zeromq heavily). 

+1

**Comment by gdamore** [comment]
I'm sorry, I've been super busy, and focused on a complete rewrite of nanomsg (C version), so this has fallen through the cracks.  I'll look later... that said, as I indicated, I'm highly skeptical that it makes sense to add some kind of transport compatibility with zmtp to go-mangos-- its likely to be far more useful to just fork it and start a zeromq-equivalent project.

I *am* available to work on such a project if someone really wants it (i.e. wants it enough to pay me for it.)  Otherwise, other projects have my priority at present.

**Comment by gdamore** [comment]
So I've looked at ZMQ a bit more, and especially ZMTP.  I can see a case to be made for using ZMTP as a transport, but that's more like an alternative to TCP or TLS.  I don't really see a case for connecting ZMQ *protocols*  with mangos/SP.  There are just too many semantic differences.

**Comment by sbinet** [comment]
Actually, after working some more on a pure-Go implementation of zmq, I agree.
Let's close this.
