### ISSUE TITLE
Head/Body concatenation?

### ISSUE THREAD

**Issue by Ranx0r0x** [go-mangos/mangos#273]
I'm writing an application that uses the pubsub mechanism paired with a pull socket.  The idea is to be able to have subscribers connect with the pub socket listening on topics they are interested in.  The pull socket is where messages are published to and it in turn passes those messages to the pub socket. 

//Send on "dateTopic" 
d := date()
header := []byte("dateTopic")
body := []byte(d)
msg := mangos.Message{Header: header, Body: body}
 testSocket.SendMsg(&msg)

//The issue is on the receiving side the header is no longer separate from the body. 

The receiving sockets that are set to listen on the dateTopic successfully receive the messages and those not setting that option do not get the message.  All is as expected.  However, when the sub socket receives the message the header is empty and the header is prepended to the body instead.

if msg, err = sock.RecvMsg(); err != nil {
			fmt.Printf("Cannot recv: %s", err.Error())
		}
		fmt.Printf("CLIENT(%s): HEADER RECEIVED %s\n", name, string(msg.Header))
		fmt.Printf("CLIENT(%s): BODY RECEIVED %s\n", name, string(msg.Body))

A sample of the output look like this:
CLIENT(C client): HEADER RECEIVED 
CLIENT(C client): BODY RECEIVED dateTopicThu Mar 16 20:20:07 2017

**Comment by gdamore** [comment]
The "Header" is reserved for protocol-specific header bits.  The PUB/SUB actually doesn't have any specific protocol header, and so its incorrect to put anything there.   (By contract, REQ protocol places routing information (backtrace) and a request ID in the header.

For PUB/SUB the entire message is *payload*.  The intention is that the header in such cases be empty.  This matches the nanomsg usage btw.

Note that the underlying protocols do not convey any special framing to indicate "this is the header", instead the protocol is expected to be able to parse off the header and stash it appropriately.  Obviously it can't do that for PUB/SUB.

If you need such framing for your application, you can do it yourself, by having a fixed length "topic" (or a separating character if you want to use variable length topics) and then handling this at the application layer.

**Comment by Ranx0r0x** [comment]
Thanks for the feedback.  That's unfortunate as the message with header is the perfect mechanism for specifying the topic/queue/destination one wishes to to send a message to.  The semantics do seem a bit confusing in this case as the SendMessage/ReceiveMessage doesn't actually work on message level but reduces it to the body alone.  From an API perspective there isn't anything that would be intuitive about that without peeling back the layers and determining what the underlying implementation is doing with it.  

I'd actually started working with setting to RAW but realized this was getting in a little deeper than what I was after as an end user. 

The design I'm looking for is to be able to have applications register themselves with a pub socket and then have another socket received a message with header/body that is then sent out to the listeners registered on the pub socket.

**Comment by gdamore** [comment]
It would be easy to create a new protocol that separated the topic into a header field.  I am not sure that is as universally useful as you think though.  It is easy enough to define your own application specific framing in the payload if you need it.

**Comment by Ranx0r0x** [comment]
I'm not sure why you think it is an edge case? What I find to be a bit of an odd pattern is firing up a pub socket that applications from hither and yon connect to directly. We want to minimize known connection points. I believe the ZeroMQ uses XPub/XSub to solve the problem. 

That's what I was looking to use Mangos for - to create a small, local broker that Go applications can connect to at start up.   There are a multiple ways to solve the problem.  I'd undoubtedly have used Mangos to solve this problem one way or another but code not fulfilling the expressed API contract is a full stop for me.  I work with too many languages, clients, and libraries to have to guess is an API means what it expresses.  A SendMessage and ReceiveMessage methods that take a Message with Header a Body have very clear semantics.  Which explicitly convey that the a Message is an atomic unit here and that it is expected to that I will send and receive those.  I understand that nanomsg didn't define it that way so that's a separate problem.

But this isn't really an issue of what is good practice in regard to brokers, queues, messages, topics, destinations, etc. It's just a fundamental software issue.  I expect a library to perform in the manner expressed by its API and if it doesn't I expect it to be considered a bug.  That isn't the case here. 

The way the library is handling this is probably the worst I can imagine.  If the given protocol can't handle messages then it shouldn't expose a message interface.  If RAW sockets can by setting the raw mode to 1? 0? true? false? or whatever then it's a specialized case of the protocol which can faithfully implement the interface requirements.

Not acceptable but better would be to strip the header off. Header, body, and payload shouldn't be semantically interchangeable as they live at different levels of abstraction.  Low level concerns about how the transports shuttle binary data across the wire shouldn't leak up into that level.  I shouldn't send a message on one side with header/body and find I receive no header on the message on the other side but that my body now has the concatenated form of header/body in the body because the underlying protocol merged them. Sending a raw []byte payload and a Message are fundamentally different levels of abstraction. 

At the very least, sending a Message across a protocol that isn't capable of handling it correctly should result in a hard break and a panic.  I should know about it right now. 

Obviously for someone like me that raises a lot of other issues. I'm putting together a set of libraries for a project I'm pitching - gorilla, boltdb, and so on.  I'm looking at ZeroMQ, Mangos, nanomsg, etc.  When I write up a quick prototype like I did and see it do what I want...sort of, I have to ask how many other cases will there be when I look at the API of the library and have to stop and say - "I wonder if it really does that or not?"

Common use cases...

RabbitMQ:
channel.basic_publish(exchange='',
                      routing_key='hello',
                      body=message)

That's a RabbitMQ routing key example.  It is essentially the same id of header/body. A more complex example would be in JMS.

Header { 
     [java]    jmsDestination  : TOPIC.testTopic.DurableSubscription[
               clientId=DurableSubscriberExample name=jms-ex1dtps selector=null]
     [java]    jmsDeliveryMode : 2
     [java]    jmsExpiration   : 0
     [java]    jmsPriority     : 4
     [java]    jmsMessageID    : ID:3-11028998375501
     [java]    jmsTimeStamp    : 1102899837550
     [java]    jmsCorrelationID: null
     [java]    jmsReplyTo      : null
     [java]    jmsType         : null
     [java]    jmsRedelivered  : false
     [java]    jmsProperties   : {}
     [java]    jmsPropReadWrite: false
     [java]    msgReadOnly     : true
     [java]    producerClientId: ID:3
     [java] }

**Comment by Ranx0r0x** [comment]
http://zguide.zeromq.org/page:all#The-Dynamic-Discovery-Problem

If you look at the Pub-Sub Envelope section in docs you'll see what I was aiming at but that's really a separate issue from how the API should honor the contract expressed.

**Comment by gdamore** [comment]
So I think the problem here is that you expect that the "topic" is part of a protocol header, distinct from the payload.  But historically the topic has always been considered to be defined as the leading part of the payload.  That definition is not intrinsic to mangos, but is really part of the nanomsg specifications that predate my involvement with nanomsg (and the existence of mangos.)

The reason I said that I don't think your definition is universal is that there are a large number of applications where the leading bytes of the payload *are* the topic.  Duplicating those in the header would be wasteful at best.

The message Header is for mangos/nanomsg/SP headers, and as I said, historically the topic isn't considered to be part of the header.

I think part of what's going on here is that you're thinking that you want certain semantics that may apply from another product, but nanomsg & co. have somewhat different semantics.  Whether those semantics are better or worse is a reasonable item for debate, but unfortunately the standards have been around for far too long, and expected by too many people, to change in the existing protocols. 

To create a new semantic, we'd not only have to break the API semantic, but also the wire protocol, so that we had a way to delimit (either by a magic byte - or more likely by prefixing with a length field) the header from the payload on the wire.  This is critical to being able to split the header from the message when it arrives on the wire.  Right now there is no such delimiter, and it is technically impossible to take an arbitrary pub message and split the topic off, because we don't know where the topic ends.

As I also indicated, its not infeasible (or even necessarily particularly difficult) to imagine creating a new "protocol" (not called pub/sub but maybe pub2/sub2 or something?) that splits the topic off into the header, and uses a length field to indicate the length of the topic in the header.

Having said that, it is hard for me to imagine that the need for such separation is sufficiently great to justify even that small amount of effort -- since its easy enough to stash a topic in other manners -- you just need to define a delimiter byte (e.g. NULL) to indicate the end of the topic.  (Unfortunately, you can't use a length field because that will confuse substring compares.)

As to "Header" and "Body" semantics.  Typically for most protocols "Headers" have a clear protocol-specific definition. That is in fact the case here, it's just that the pub/sub protocol doesn't actually have any interesting header data (unlike say REQ/REP), since we assume the topic is part of the payload.  (And as indicated, whether good or bad, the precedent and wire protocol for this were established years ago.)
