### ISSUE TITLE
Return error on timeout in Req/Rep

### ISSUE THREAD

**Issue by vagoff** [go-mangos/mangos#286]
Supposing the following scenario:
1. Client does REQ
2. REP Server accepts REQ and executes it
3. Server dies (kill -9 goes)
4. Client still waits for response
5. Server restarts
6. Client reconnects and waits for response for ever

How about failing with timeout from client req instead of hanging on entire distributed system forever?

**Comment by gdamore** [comment]
The client has logic to reissue the request in this case.

**Comment by vagoff** [comment]
I performed the following experiment:
1. Take examples/reqrep/reqrep.go
2. Insert line
			time.Sleep(time.Duration(5) * time.Second)
after
			fmt.Println("NODE0: RECEIVED DATE REQUEST")
3. Run ./reqrep node0 tcp://127.0.0.1:40899 
4. Run ./reqrep node1 tcp://127.0.0.1:40899 on another terminal
5. Ctrl-Z and kill -9 %% on server terminal
6. Restart server
7. Wait for 10 minutes
8. Client is still waiting for response.

How to enable that retry logic you mentioned?

**Comment by gdamore** [comment]
Seems like a bug... the logic should be there all the time.
Having said that, when you restarted the server did you verify that it was able to bind to the port specified?  Normally TCP interjects a FIN_WAIT...  and the server restart might have been the thing that broke.

netstat -af inet -n | grep 40899 might be informative.

**Comment by vagoff** [comment]
I've just repeated the experiment with addition that is to open 3rd terminal at step 6a and running new node1 client several times -- it worked properly. While previous client is being hanged.

**Comment by gdamore** [comment]
Maybe you've discovered an edge case somewhere, I'm looking at the code now... it's been a few years since I've been in this code, so please be patient.

**Comment by gdamore** [comment]
So, the logic that I thought was there -- to automatically go into retry state on pipe removal, and restart on addition (and unfortunately I used "Endpoint" in mangos parlance, whereas nanomsg and nng use "endpoint" to mean something else... argh, but totally my fault there) is missing.

Pretty sure I know what needs to be done to fix, give me a little bit.  If you haven't heard back with a fix from me in the next couple of days, please re-ping me.

**Comment by vagoff** [comment]
Thanks! I do want to hurry or force you in any way. Thanks for the excellent work!

**Comment by mrLSD** [comment]
Hi, it's really important feature for us.
Currently we discuss decline go-mongos, because it's problems with timeout.
Will it any settings for that?
We need it as soon as it possible.

Thanks for the excellent work!

**Comment by gdamore** [comment]
I'll probably get to this this weekend.  Sorry for the delays.  Was pretty busy with some other tasks recently.

For the record, one way to "expedite" is to "reprioritize" my work by sponsoring it or paying for commercial support.  Folks who pay for support get priority access; otherwise its just as I have to get to it.

**Comment by gdamore** [comment]
So ... test added... PR submitted, will wait for CI to verify results -- the test suite is pretty fragile.

While here I noticed that I really want to redesign the req/rep protocol -- this implementation represents my earlier thinking and turns out to be a bit naive -- the pipes just all blindly pull , and there is no knowledge of the other pipes.  This means that load balancing is unpredictable, and that their ignorance of each other makes properly resubmitting the request to the *same* pipe challenging.

Still, the changes in the current PR should address your immediate needs.

**Comment by mrLSD** [comment]
@gdamore Thankful for your awesome work!

**Comment by mrLSD** [comment]
As I understand timout still not implemented for case:
`sockreq.Recv();`

For example after wating 30 sec `sockreq.Recv()` return an error?

**Comment by gdamore** [comment]
No, you'll still get a timeout.  The missing piece here is that the timeout for that won't cancel the outstanding send request.  (Meaning under the hood mangos will still keep trying to send those req requests until you cancel it by sending some other message, even though the receive side has already reported a timeout to you.)  The tests I wrote don't cover receive timeout logic.

**Comment by gdamore** [comment]
Specifically, #290 is not fixed.

**Comment by grrtrr** [comment]
#### Please clarify - this does not seem to be a bug at all

In light of #296, #298, #299, #300 (problems with spurious retransmissions we are experiencing) I have spent half a day trying to reproduce the above problem.

What I discovered is this caveat in using the `examples/reqrep/reqrep.go`, in that it uses _default values_ for most of mango's timers. In particular the _receive timeout_ (sock.rdeadline)
is _not_ set, which means that the `<-timeout` in core.go:RecvMsg() will never return.

Req/rep has several timeouts and default values for queue length that must be carefully tuned in order for the protocol to operate as intended. I drew up the following picture to
illustrate this:

![nanomsg](https://user-images.githubusercontent.com/5132989/34321995-1e1f081a-e7d9-11e7-8e67-54400b250473.jpeg)

| Name in Image | Mangos Socket Option | Default |
|--------------------|------------------------------|--------:|
|  Receive timeout  |  `OptionRecvDeadline`  | `nil` (infinite) |
| Send timeout        |  `OptionSendDeadline` | zero `time.Time{}` (i.e. in the past) |
|  recon                  |  `OptionReconnectTime`| 100msec |
| reconMax            |  `OptionMaxReconnectTime`| 0 |

One more thing I found of significance is the _queue length_, which by default is 128. I found it interfered with scenarios such as this one and so prefer to set it to 1.

Now, since the receive timeout is not set by default, the simple `reqrep.go` in the `examples/` directory will indeed appear to "hang" infinitely, simply because its receive timeout has
not been set. I have test files that allow to test for each of the robustness cases (crashing server, reconnecting client, restarting server, slow server), by exposing the above socket options.

_Question_: Given that this seems to depend on initialization (I'd be happy to provide the files for testing), I do not think that the above is a bug. The fix that was introduced for #286, I am not sure it is needed. I have found go-mangos to be well-architected. Given that there are now 4 other problems that arose after the fix (#296, #298, #299, #300 - likely duplicates), would it please
be possible to revisit this issue, and perhaps revert the fix for a problem that would not exist if a mangos socket option had been set (maybe adding a timeout to the reqrep.go would make it
easier to play with the protocol)?

**Comment by gdamore** [comment]
So #298,  #299, and #300 are all the same problem.    I will probably close two of them as dups of the other.

The close race I need to investigate.

It would appear that I screwed this up, and it may be better to revert this change.  HOWEVER, the underlying issue that REQ does not issue retries properly when a REP server dies MUST be addressed. 

This particular bug report is a bit confusing because several different issues were conflated here.  Not getting an error report back is only one dimension of the issue -- that is indeed "not a bug", but rather just an issue of setting the receive timeout properly.

The fact that the server won't restart properly due to bind() failing is also "not a bug". 

What *is* a bug is that REQ (before the change) does not issue a retry until its entire timeout passes.  What I tried to do (and may have botched here) is to have REQ notice when the REP pipe it sent a request dies or disconnects, and to automatically reissue the REQ without waiting for the retry timeout to expire.  This is supposed to offer a "fast recovery" from such a situation.

**Comment by grrtrr** [comment]
Thank you. I am not sure I understand the issue of the req not retrying properly when a rep server dies:
- I have tested this quite a bit (the example program in #301 has a `-crash` option to let the server die),
- the req re-issues according to _send timeout_ and _retry interval_,
- even if the server dies (if I remember correctly I tested this as part of evaluating go-mangos a year ago).

My thinking currently is that the issues seen evolve around timeouts; if this is not the case, could you please clarify what the underlying issue is?

I have successfully been able to reissue requests after a crashing  server restarted.

**Comment by gdamore** [comment]
The issue is a desire for “fast recovery”. There is no point in waiting for
the timeout if the peer has disconnected. Anyway I think its fixed now.
