### ISSUE TITLE
Exponential backoff in reconnect

### ISSUE THREAD

**Issue by vagoff** [go-mangos/mangos#287]
After quick tcpdump analysis it seems the library reconnects without slowing down. How about usual exponential backoff?
E.g. reconnect after 0 milliseconds, 1, 2, 4, 8, 16, ... 1min, 5min, 5min, 5min, or something in the vein.

**Comment by vagoff** [comment]
```
$ cat check.sh
mkdir tmp
cd tmp
git clone https://github.com/go-mangos/mangos.git
cd mangos/examples/reqrep
go build
timeout 30 ./reqrep node1 tcp://127.0.0.1:40899 &
sleep 10
sudo timeout 10 tcpdump -i lo port 40899 | wc

$ bash check.sh
NODE1: SENDING DATE REQUEST DATE
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
182 packets captured
396 packets received by filter
0 packets dropped by kernel
    183    3276   23143
```

**Comment by gdamore** [comment]
It is in fact possible to configure this with tunables that exist in the library.

See OptionReconnectTime and OptionMaxReconnectTime.  By default the library doesn't have a backoff (by design)  You set OptionMaxReconnectTime to non-zero, then the reconnect interval doubles each attempt, until it hits that maximum time.  If the value is zero (default), then no backoff is used, and OptionReconnectTime is used every time.

**Comment by vagoff** [comment]
Thanks for clarification!
