### ISSUE TITLE
Investigate new sync.Pool for message pooling

### ISSUE THREAD

**Issue by gdamore** [go-mangos/mangos#33]
It may be faster/better to use sync.Pool for Go message pooling.  In the past we found it was slightly less efficient than our hand coded version using channels, but Go 1.4 may have improved here.  We should investigate again.

**Comment by gdamore** [comment]
One reason, apart from performance, not to do this right away is that gccgo is not up to v1.4.  There's no particular hurry here.

**Comment by gdamore** [comment]
Gcc 5.3 provides Go 1.4.2.  Plan is for go 1.5 to come with gcc 6.  Time to take another look, I think.  Also, instead of channels, perhaps a queue interface with a lock would be preferable?  It seems to me that in the past use of explicit locking primitives typically outperformed channels.

**Comment by logrusorgru** [comment]
Is there a benchmark for the cache? If so, how to run it?

**Comment by gdamore** [comment]
There isn't one.  I wrote a version and used the existing performance tests.

**Comment by erikdubbelboer** [comment]
I would just use sync.Pool. In benchmarks it out performs any other solution by far: http://blog.dubbelboer.com/2016/05/21/sync-vs-chan-pool.html

**Comment by gdamore** [comment]
Hmmm. Ok cool.  This was not the case in the past. :)

**Comment by logrusorgru** [comment]
The problem will never solved. A `sync.Pool`is effective only if pieces of a data freed/allocated between GC pauses. So, it's good for very fast and high loaded applications. But for slightly less loaded applications the `sync.Pool` is the same as GC (with some overhead). Too many things depends on network throughput (if network is used) and an application loading. Also, keep in mind that `sync.Pool` works more effective if an allocation and a release perform in the same OS thread. The pros of a chan pool is using of some preallocated pieces that will never freed. For example if I use PUSH and size of my messages is around 32 byte only. I can allocate OptionWriteQLen pieces (and never free them) and use this. In this particular case I can rid out off any GC-pressure. Yeah. it's very specific. Actually each application requires its own approach. And yes - for most cases `sync.Pool` is a best choose (since go1.5 or go1.6). The only one solution I can see is:

1. Make a Pool interface
2. Provide a configurable Pool based on channels (optional)
3. Provide a configurable Pool based on `sync.Pool` (optional)
4. Provide a Pool that do nothing (`make([]byte, 0, size)`). (optional)
5. Provide an ability to use own pool.
6. Let the end user solves this problem (for his particular case).

Or

1. Just move to `sync.Pool`

Let's see my research: https://gist.github.com/logrusorgru/a032bd8a7da1ed4fcb5afa7ee79f9980
I can only run the benchmarks (from my research) only on 2 physical CPU cores. Also, benchmarks with delay are not correct.

**Comment by gdamore** [comment]
Its still not clear.  sync.Pool might be a win, and admittedly for a lightly loaded server it probably doesn't matter a lot.  sync.Pool has distinct optimizations which allow it to operate without strict concurrency guards, using separate caches for CPUs.  (This is very similar to per-cpu kmem_cache magazines for those familiar with the Solaris slab allocator.)  In extreme load situations, sync.Pool is almost certainly faster.  It will also scale up its memory consumption automatically in this circumstance, but this is exactly the right thing to do -- it should avoid certain "cliffs" in performance of the buffered channel.  (Which occurs when we have particular bursty traffic with a burst >= size of the channel capacity.)

I'm going to still use separate sync.Pools sorted on object size to balance the load, and this should reduce some kinds of pressure (small objects probably get consumed at a much larger rate than large ones).

Note that sync.Pool has one drawback (aside from not existing prior to Go 1.3) -- that is that it may actually wind up holding more objects than we really need by a factor of GOMAXPROCS.  Probably still a win.

**Comment by gdamore** [comment]
So testing is quite interesting.  As expected, the sync.Pool wins *huge* with large message sizes.  With small message sizes, and less concurrency, it seems to matter less.
